### ISSUE TITLE
sed error message

### ISSUE THREAD

**Issue by cleesmith** [pierlauro/playlist2links#10]
The script seems to extract the first 100 then this error:
`sed: 1: "/tmp/./playlist2links.t ...": invalid command code .`
... this happens with or without the **withnames** option, example:
`./playlist2links PLK_NHLbnG-k_iilj5bn6mGVR6OK4jhNcY withnames`
... on a macOS Sierra 10.12.6

Update: after changing line 46 to:
`sed -i "" 's/_continuation=1/\n/g' $TMPFILE`
... the error message is gone, but there are still only 100 items in the text file results.

Thoughts?
Thanks,
Chris

**Comment by pierlauro** [comment]
Seems that Youtube recently changed its request format so the parsing for long playlists was not working anymore. Just fixed, pull the [new version](https://github.com/pierlauro/playlist2links/tree/master).

**Comment by cleesmith** [comment]
Works great ... wow, that was a fast fix and response ... thank you!

**Comment by pierlauro** [comment]
You're welcome!
