### ISSUE TITLE
Only extracts the first 100 links, even with playlist that are bigger.

### ISSUE THREAD

**Issue by CamilleScholtz** [pierlauro/playlist2links#2]
example: https://www.youtube.com/playlist?list=PLvqif5Ve8JbkTGXQ6gVuebpnUaEkUYCZA

**Comment by pierlauro** [comment]
I just [committed](https://github.com/pierlauro/playlist2links/commit/47cea9f9ce3dc53167f54573557719baeac79ce0) the fix.

I never noticed this problem, the script is now able to follow ajax requests for big playlists! ;)
