### ISSUE TITLE
Freezes after 200 links in 500 link playlist

### ISSUE THREAD

**Issue by mypetbirdrules** [pierlauro/playlist2links#3]
I ran the script on a YouTube playlist with more than 500 videos and the script froze after 200 links were extracted.

**Comment by pierlauro** [comment]
[SOLVED](https://github.com/pierlauro/playlist2links/commit/ccc20f8d705dfd170bee00c270b4a53a62c77cd7)

**Comment by marado** [comment]
This seems to be still not working (or, perhaps, again not working).

**Comment by pierlauro** [comment]
It was extremely slow but working (Youtube response size is bigger than last year).
Anyway, I just pushed this [COMMIT](https://github.com/pierlauro/playlist2links/commit/031cb6325aee8112b411d451e2589c6cc85a8326) to fix the problem.
