### ISSUE TITLE
withnames not working

### ISSUE THREAD

**Issue by johnpeterch** [pierlauro/playlist2links#9]
So ./playlist2links 123CODEOFPLAYLIST withnames is no longer outputting titles + links. It only outputs links. Can you check what's going on?

**Comment by pierlauro** [comment]
Hi, could you please paste the command you're running? I just tried on a couple of playlists and it's actually working.

**Comment by johnpeterch** [comment]
./playlist2links PLE720EF13D4C23DDC withnames

That's the exact command I'm running for a public playlist. I only get the links back. 
I tried it on one of my own playlists and it only returns the links as well

**Comment by pierlauro** [comment]
Still working on my machine.
Could you please post the output of the following command?
```
curl -s 'https://www.youtube.com/playlist?list=PLE720EF13D4C23DDC' | grep -e "^<tr.*<a href=\"/watch?v=.*$1"
```

**Comment by johnpeterch** [comment]
Sure, see attached

[output.txt](https://github.com/pierlauro/playlist2links/files/1731586/output.txt)

**Comment by pierlauro** [comment]
The output is the expected one, the only issue could be in `sed`. What's the output of `sed --version` ?

**Comment by johnpeterch** [comment]
`sed --version` returns:

`sed: illegal option -- -
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]`

I'm running Mac OS High Sierra 10.13.2

**Comment by pierlauro** [comment]
Got it! Mac OS is using bsd's sed that is not supporting gnu's newline's escaping (`\n`).

I just pushed a [new version](https://github.com/pierlauro/playlist2links/commit/715d14c9edd01241f9923b3d20eb03b058b6f068) working with both sed variants.

**Comment by johnpeterch** [comment]
That's awesome! And It's working :) A BIG thank you!
